# Generated by Django 5.0.4 on 2024-05-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_option_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='defficulty',
            new_name='difficulty',
        ),
    ]
