# Generated by Django 5.0.4 on 2024-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_defficulty_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
